when:
  - event: [pull_request, tag, cron, push]

steps:
  - name: run-tests
    image: bjodah/bjodahimg20:21.8
#    privileged: true  # or in the future(?): --cap-add SYS_PTRACE
    environment:
      - CC=gcc-11
      - CXX=g++-11
      - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-12/bin/llvm-symbolizer
      - ASAN_OPTIONS=symbolize=1
      - CFLAGS=-Werror -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
    commands:
      - ANYODE_NO_LAPACK=1 ./scripts/ci.sh
      - ANYODE_NO_LAPACK=0 ./scripts/ci.sh
